services:
  ckan:
    image: ckan/ckan-base:2.11
    networks:
      - ckannet
      - dbnet
      - solrnet
      - redisnet
    environment:
      TZ: UTC
      CKAN_SITE_ID: default
      CKAN_SITE_URL: https://localhost:8443
      CKAN_SQLALCHEMY_URL: postgresql://ckandbuser:ckandbpassword@db/ckandb
      CKAN_DATASTORE_WRITE_URL: postgresql://ckandbuser:ckandbpassword@db/datastore
      CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:datastore@db/datastore
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_DATAPUSHER_URL: http://datapusher:8800
      CKAN__DATAPUSHER__CALLBACK_URL_BASE: http://ckan:5000
      CKAN__PLUGINS: image_view text_view datatables_view datastore datapusher envvars
      CKAN__HARVEST__MQ__TYPE: redis
      CKAN__HARVEST__MQ__HOSTNAME: redis
      CKAN__HARVEST__MQ__PORT: 6379
      CKAN__HARVEST__MQ__REDIS_DB: 1
      CKAN___SECRET_KEY: g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
      CKAN___BEAKER__SESSION__SECRET: g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
      CKAN___API_TOKEN__JWT__ENCODE__SECRET: string:g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
      CKAN___API_TOKEN__JWT__DECODE__SECRET: string:g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data/ckan:/var/lib/ckan
      - ./data/pip_cache:/root/.cache/pip
      - ./data/site_packages:/usr/lib/python3.10/site-packages
      - ./ckan/apply_patches.sh:/apply_patches.sh:ro
      - ./ckan/patches:/app/patches:ro
      - ./ckan/docker-entrypoint.d:/docker-entrypoint.d:ro
    command: ["/bin/bash", "/apply_patches.sh"]
    restart: always
    ports:
      - "5000:5000"

  datapusher:
    networks:
      - ckannet
      - dbnet
    image: ckan/ckan-base-datapusher:0.0.21
    restart: always
    ports:
      - "8800:8800"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      CKAN_DB_USER: ckandbuser
      CKAN_DB_PASSWORD: ckandbpassword
      CKAN_DB: ckandb
      DATASTORE_READONLY_USER: datastore_ro
      DATASTORE_READONLY_PASSWORD: datastore
      DATASTORE_DB: datastore
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dbnet

  solr:
    networks:
      - solrnet
    image: ckan/ckan-solr:2.10-solr9
    volumes:
      - ./data/solr:/var/solr
    restart: always
    ports:
      - "8983:8983"

  redis:
    image: redis:6
    networks:
      - redisnet
    ports:
      - "6379:6379"
    restart: always

networks:
  webnet:
  ckannet:
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true
