apiVersion: v1
data:
  apply_patches.sh: |
    #!/bin/bash

    set -e

    for d in /app/patches/*; do
      if [ -d "$d" ]; then
        for f in "$d"/*.patch; do
          echo "Applying patch $f in $(basename "$d")"
          cd "/usr/lib/ckan/$(basename "$d")"
          patch -p1 < "$f"
        done
      fi
    done

    exec ckan run
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: ckan
  name: ckan-cm3
