apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ckan
  name: ckan
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ckan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ckan
    spec:
      containers:
        - name: ckan
          image: ckan-unime:latest
          imagePullPolicy: Never
          env:
            - name: CKAN_DATAPUSHER_URL
              value: http://datapusher:8800
            - name: CKAN_DATASTORE_READ_URL
              value: postgresql://datastore_ro:datastore@db/datastore
            - name: CKAN_DATASTORE_WRITE_URL
              value: postgresql://ckandbuser:ckandbpassword@db/datastore
            - name: CKAN_REDIS_URL
              value: redis://redis:6379/1
            - name: CKAN_SOLR_URL
              value: http://solr:8983/solr/ckan
            - name: CKAN_SITE_ID
              value: default
            - name: CKAN_SITE_URL
              value: https://localhost:8443
            - name: CKAN_SQLALCHEMY_URL
              value: postgresql://ckandbuser:ckandbpassword@db/ckandb
            - name: CKAN__DATAPUSHER__CALLBACK_URL_BASE
              value: http://ckan:5000
            - name: CKAN__HARVEST__MQ__HOSTNAME
              value: redis
            - name: CKAN__HARVEST__MQ__PORT
              value: "6379"
            - name: CKAN__HARVEST__MQ__REDIS_DB
              value: "1"
            - name: CKAN__HARVEST__MQ__TYPE
              value: redis
            - name: CKAN__DATAPUSHER__API_TOKEN
              value: g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
            - name: CKAN__PLUGINS
              value: image_view text_view datatables_view datastore datapusher envvars
            - name: CKAN___SECRET_KEY
              value: g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
            - name: CKAN___API_TOKEN__JWT__DECODE__SECRET
              value: string:g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
            - name: CKAN___API_TOKEN__JWT__ENCODE__SECRET
              value: string:g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
            - name: CKAN___BEAKER__SESSION__SECRET
              value: g0P3BqsJxJv3_cUE3eT9N8lYZ4qkQz1DJBiTD6Nzm9Y
            - name: TZ
              value: UTC
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            #- mountPath: /var/lib/ckan
            #name: ckan-claim0
            - mountPath: /root/.cache/pip
              name: ckan-claim1
            - mountPath: /usr/lib/python3.10/site-packages
              name: ckan-claim2
            - mountPath: /usr/lib/ckan/default
              name: ckan-claim2
            - mountPath: /docker-entrypoint.d
              name: ckan-cm5
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ckan-claim0
          persistentVolumeClaim:
            claimName: ckan-claim0
        - name: ckan-claim1
          persistentVolumeClaim:
            claimName: ckan-claim1
        - name: ckan-claim2
          persistentVolumeClaim:
            claimName: ckan-claim2
        - configMap:
            name: ckan-cm5
          name: ckan-cm5
