apiVersion: batch/v1
kind: Job
metadata:
  name: ckan-dcatapit-loader
spec:
  template:
    spec:
      containers:
        - name: ckan-dcatapit-loader
          image: your-ckan-image:latest # Replace with your CKAN image
          env:
            - name: CKAN_CONFIG
              value: /etc/ckan/default/production.ini
          command: ["/bin/sh", "-c"]
          args:
            - |
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/languages-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/data-theme-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/places-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/frequencies-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/filetypes-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/theme-subtheme-mapping.rdf --eurovoc vocabularies/eurovoc-filtered.rdf && \
              ckan -c /etc/ckan/default/ckan.ini dcatapit load --filename=vocabularies/licences.rdf
          volumeMounts:
            - name: vocabularies-volume
              mountPath: /vocabularies # Adjust path as needed
      restartPolicy: Never
      volumes:
        - name: vocabularies-volume
          configMap:
            name: your-vocabularies-configmap # Or use a PVC or other volume source
  backoffLimit: 1
