apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ckan
  name: ckan
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ckan
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ckan
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - " for d in /app/patches/*; do\n  if [ -d  ]; then\n    for f in $()(ls /*.patch | sort -g); do\n      cd /usr/lib/ckan/$()(basename ) && patch -p1 < ;\n    done;\n  fi;\ndone && /docker-entrypoint.sh "
          env:
            - name: CKAN_DATAPUSHER_URL
              value: http://datapusher:8800
            - name: CKAN_DATASTORE_READ_URL
              value: postgresql://datastore_ro:datastore@db/datastore
            - name: CKAN_DATASTORE_WRITE_URL
              value: postgresql://ckandbuser:ckandbpassword@db/datastore
            - name: CKAN_REDIS_URL
              value: redis://redis:6379/1
            - name: CKAN_SITE_ID
              value: default
            - name: CKAN_SITE_URL
              value: https://localhost:8443
            - name: CKAN_SQLALCHEMY_URL
              value: postgresql://ckandbuser:ckandbpassword@db/ckandb
            - name: CKAN__DATAPUSHER__CALLBACK_URL_BASE
              value: http://ckan:5000
            - name: CKAN__HARVEST__MQ__HOSTNAME
              value: redis
            - name: CKAN__HARVEST__MQ__PORT
              value: "6379"
            - name: CKAN__HARVEST__MQ__REDIS_DB
              value: "1"
            - name: CKAN__HARVEST__MQ__TYPE
              value: redis
            - name: CKAN__PLUGINS
              value: image_view text_view datatables_view datastore datapusher envvars
            - name: CKAN___API_TOKEN__JWT__DECODE__SECRET
              value: string:CHANGE_ME
            - name: CKAN___API_TOKEN__JWT__ENCODE__SECRET
              value: string:CHANGE_ME
            - name: CKAN___BEAKER__SESSION__SECRET
              value: CHANGE_ME
            - name: TZ
              value: UTC
          image: ckan/ckan-base:2.11
          livenessProbe:
            exec:
              command:
                - wget
                - -qO
                - /dev/null
                - http://localhost:5000/api/action/status_show
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          name: ckan
          volumeMounts:
            - mountPath: /var/lib/ckan
              name: ckan-storage
            - mountPath: /root/.cache/pip
              name: pip-cache
            - mountPath: /usr/lib/python3.10/site-packages
              name: site-packages
            - mountPath: /docker-entrypoint.d
              name: ckan-cm3
              readOnly: true
            - mountPath: /app/patches
              name: ckan-cm4
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ckan-storage
          persistentVolumeClaim:
            claimName: ckan-storage
        - name: pip-cache
          persistentVolumeClaim:
            claimName: pip-cache
        - name: site-packages
          persistentVolumeClaim:
            claimName: site-packages
        - configMap:
            name: ckan-cm3
          name: ckan-cm3
        - configMap:
            name: ckan-cm4
          name: ckan-cm4
