apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datapusher
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: datapusher
    spec:
      containers:
        - image: ckan/ckan-base-datapusher:0.0.21
          livenessProbe:
            exec:
              command:
                - wget
                - -qO
                - /dev/null
                - http://localhost:8800
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          name: datapusher
          ports:
            - containerPort: 8800
              protocol: TCP
      restartPolicy: Always
