apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datapusher
  template:
    metadata:
      labels:
        io.kompose.service: datapusher
    spec:
      containers:
        - image: ckan/ckan-base-datapusher:0.0.21
          livenessProbe:
            exec:
              command:
                - wget
                - -qO
                - /dev/null
                - http://127.0.0.1:8800
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          name: datapusher
          ports:
            - containerPort: 8800
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
