apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    io.kompose.service: datapusher
