apiVersion: v1
data:
  .gitattributes: |
    *.sh text eol=lf
  10_create_ckandb.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE ROLE "$CKAN_DB_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$CKAN_DB_PASSWORD';
        CREATE DATABASE "$CKAN_DB" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    EOSQL
  20_create_datastore.sh: |-
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE ROLE "$DATASTORE_READONLY_USER" NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATASTORE_READONLY_PASSWORD';
        CREATE DATABASE "$DATASTORE_DB" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    EOSQL
  30_setup_test_databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE ckan_test OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
        CREATE DATABASE datastore_test OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    EOSQL
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db
  name: db-cm1
