apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: CKAN_DB
              value: ckandb
            - name: CKAN_DB_PASSWORD
              value: ckandbpassword
            - name: CKAN_DB_USER
              value: ckandbuser
            - name: DATASTORE_DB
              value: datastore
            - name: DATASTORE_READONLY_PASSWORD
              value: datastore
            - name: DATASTORE_READONLY_USER
              value: datastore_ro
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim0
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
        - configMap:
            name: db-cm1
          name: db-cm1
