apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: solr
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 8983:8983 /var/solr"]
          volumeMounts:
            - name: solr-claim0
              mountPath: /var/solr
      containers:
        - image: ckan/ckan-solr:2.11-solr9
          name: solr
          ports:
            - containerPort: 8983
              protocol: TCP
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /var/solr
              name: solr-claim0
      restartPolicy: Always
      volumes:
        - name: solr-claim0
          persistentVolumeClaim:
            claimName: solr-claim0
