apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kompose-files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: solr
    spec:
      containers:
        - image: ckan/ckan-solr:2.10-solr9
          name: solr
          ports:
            - containerPort: 8983
              protocol: TCP
          volumeMounts:
            - mountPath: /var/solr
              name: solr-claim0
      restartPolicy: Always
      volumes:
        - name: solr-claim0
          persistentVolumeClaim:
            claimName: solr-claim0
