apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckan-pv-claim2
  labels:
    io.kompose.service: ckan-claim2
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/ckan-claim2
