apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-claim0
  labels:
    io.kompose.service: db-claim0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/db-claim0
