apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-pv-claim0
  labels:
    io.kompose.service: solr-claim0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/solr-claim0
